---
substitutions:
  name: "m5stack-atom-echo-X"
  friendly_name: M5Stack Atom Echo X
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ota_password: !secret ota_password

packages:
  remote_package:
    url: https://github.com/HLandstrom/firmware/
    ref: main
    file: voice-assistant/m5stack-atom-echo.yaml.yaml
    refresh: 0s
